#!/bin/bash

# set-vm-power --- Set the vm's power state.
# Tell the vm to change power state.
# Available states are: hibernate, off, on, reboot, reset, shutdown, suspend

# Author: Mike Barker <mike@thebarkers.com>
# Created: September  2, 2015

# History:
# 2015.09.02
# * First release.

# 2015-10-04
# * Added optional argument handling via getopts.
#   Now you can specifiy a username and/or server

# 2015-10-13
# * Removed parameters for username and server (-u and -s)
#   Now require a server and optionaly a username in the standard
#   user@server format.

function show_help {
    echo "usage: $(basename $0) [-h|-?] [user@]hostname state vmid"
    echo ""
    echo "       -h|-? : Print this help"
    echo "        user : Optional user to connect to the host as."
    echo "    hostname : The host to connect to."
    echo "       state : The power state to be set:"
    echo "               hibernate, off, on, reboot, reset,shutdown, suspend."
    echo "        vmid : the virtual machine id (use get-allvms to find)"
}

OPTIND=1
while getopts "h?" opt; do
    case "$opt" in
	h|\?)
	    show_help
	    exit 0
	    ;;
    esac
done
shift $((OPTIND-1))
[ "$1" = "--" ] && shift

# Check for required server
if [ -z "$1" ]; then
    show_help
    exit -1
fi

# Check for required power state
if [ -z "$2" ]; then
    show_help
    exit -2
fi

# Check for required vmid
if [ -z "$3" ]; then
    show_help
    exit -3
fi

# Set the power state
./vim-cmd $1 "vmsvc/power.$2" $3
