#!/bin/bash
# vim-cmd --- Run a vim-cmd command on a vsphere/esxi server
# Use ssh to run the vimsh passing in a vim-cmd command to be run.

# Author: Mike Barker <mike@thebarkers.com>
# Created: September  2, 2015

# History:
# 2015-09-02
# * First release.

# 2015-10-04
# * Add optional argument support via getopts(1).
#   This allows the user name and/or server to be specified on the command line.
# * Now allows any vim-cmd command to be run.

# 2015-10-13 MRB
# * Removed parameters for username and server (-u and -s)
#   Now require a server and optionaly a username in the standard
#   user@server format.

function show_help {
    echo "usage: `basename $0` [-h|-?] [user@]hostname command"
    echo ""
    echo "       -h|-? : Print this help"
    echo "        user : Optional user to connect to host as"
    echo "    hostname : The host to connect to"
    echo "     command : The vim-cmd command to run on the host"
    echo "               or leave blank to see a list of avialable comands"
}

# Handle command line parameters
OPTIND=1
while getopts "h?" opt; do
    case "$opt" in
	h|\?)
	    show_help
	    exit 0
	    ;;
    esac
done
shift $((OPTIND-1))
[ "$1" = "--" ] && shift

# Check for required parameters
if [ -z "$1" ]; then
    show_help
    exit -1
fi

server=$1
shift

ssh $server "vim-cmd $@"
